import Head from 'next/head'
import Image from 'next/image'
import { MutableRefObject, useRef, useState } from 'react'
import styles from '../styles/Home.module.css'
import BlogSection from './components/BlogSection'
import ContactSection from './components/ContactSection'
import LandingSection from './components/LandingSection'
import IntroSection from './components/IntroSection'
import ProjectsSection from './components/ProjectsSection'
import WorkExperienceSection from './components/WorkExperienceSection copy'

export default function Home() {

  const sectionRefs: MutableRefObject<{ [key: string]: any }> = useRef({});


  return (
    <div className={''}>
      <Head>
        <title>Personal Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={''}>
        <LandingSection handleCollectionClick={handleCollectionClick} />

        <IntroSection ref={(element: any) => sectionRefs.current['Introduction'] = element} />
        <ProjectsSection ref={(element: any) => sectionRefs.current['Projects'] = element} />
        <WorkExperienceSection ref={(element: any) => sectionRefs.current['WorkExperience'] = element} />
        <BlogSection ref={(element: any) => sectionRefs.current['Blog'] = element} />
        <ContactSection ref={(element: any) => sectionRefs.current['Contact'] = element} />


      </div>

    </div >
  )

  function handleCollectionClick(collection: string) {
    if (collection.split(':')[0] !== 'Random') {
      sectionRefs.current[collection].scrollIntoView({ behavior: 'smooth' })
    }
  }
}
